// playground/src/scripts/App.svelte
<script lang="ts">
  import store from 'scripts/store';
  import connect from 'diox/connectors/svelte';

  const useCombiner = connect(store);
  const router = useCombiner<{ test: string }>('router', (newState) => ({
    test: newState.route,
  }));

  function goToTestPage(): void {
    store.mutate('router', 'NAVIGATE', '/test');
  }
  function goToHomePage(): void {
    store.mutate('router', 'NAVIGATE', '/');
  }
</script>

<section>
  <p>You are here: {`http://localhost:5030${$router.test}`}</p>
  {#if $router.test === '/'}
    <button on:click={goToTestPage}> Go to /test page </button>
  {:else}
    <button on:click={goToHomePage}> Go to / page </button>
  {/if}
</section>

// playground/src/scripts/App.vue
<template>
  <section>
    <p>You are here: {{ url }}</p>
    <button
      v-if="route === '/'"
      @click="goToTestPage"
    >
      Go to /test page
    </button>
    <button
      v-else
      @click="goToHomePage"
    >
      Go to / page
    </button>
  </section>
</template>

<script lang="ts">
import store from 'scripts/store';
import useStore from 'diox/connectors/vue';

const [useCombiner, mutate] = useStore(store);

export default useCombiner('router', {
  computed: {
    url(): string {
      return `http://localhost:5030${(this as unknown as { route: string; }).route}`;
    },
  },
  methods: {
    goToTestPage(): void {
      mutate('router', 'NAVIGATE', '/test');
    },
    goToHomePage(): void {
      mutate('router', 'NAVIGATE', '/');
    },
  },
});
</script>
